language: ruby
rvm:
- 2.2.3
notifications:
  slack:
    secure: D/KgyfwUfYKzLf86BlND9XM4f/8spR5P2zzECbvrFCG2RMxcg1n2rzidJHZl46DvkGm0NCGNe3q4zYi9u7FivG3++dvox1UKnq3PEwnBqqWW76b3ZMnfA7D/gmi+sF182lPlxHjCgZGSOgV6aFGndkjMPh0NH+KPo+gkDNenoUAoq/JEu+qo5IKWV2vXLgZcl4vGH2/JZRei2pfnlkA0yNY2ziLw2ZOphD14D4LN4Vm1O+NwWHFA6JJmjlzezgzbXPBBq/0Lx1ZrYsNgf3Jpao448bNT5VoJJ3nXjRRyVvXzwL/lporKrOThszf09vERi/FqAAFox//d/YQgcOt1CCArZECDVp8r3m0UelKss6O2JksRn1V/N4fXhG47SpuzUgRKH5RHm3/kTdunhHefH5mNuQJ+Fh37VYCEk729l+Jh2igrofGkMwwUevplRrD45j27EejOu6+U7ij47Y4HQV6Tqg6ptXOE+Iq2yu3n/gpiMlhjw1juqQATjYNbcwZ1IvQgQF93VcdyVmi6XrDvbLyNIqhMpxhbsAnzwQ7IFa9KZ1J32aE4jJgjMuQGetNmNfHEg5lO8ADDzXO9KHHbJXhDv4wP5rjMLYo4V8ogaN7Nd06TXyPpPQ4EenJ+SBcY/PPogeOt3DQplJqbOqlzP0/2Bs4SqJ8IMWKOD4yZ/Lo=
